/**
 * @openapi
 * components:
 *   schemas:
 *     UpdateDockerConfigDto:
 *       type: object
 *       description: Data Transfer Object for updating Docker configuration.
 *       properties:
 *         useCustomDockerfile:
 *           type: boolean
 *         dockerfileLocation:
 *           type: string
 *           description: Relative path to the Dockerfile in the repository.
 *           nullable: true
 *         baseImage:
 *           type: string
 *           description: Base image if Dockerfile is generated by Idem.
 *           nullable: true
 *         registryUrl:
 *           type: string
 *           description: URL of the Docker registry (e.g., ECR, GCR, ACR).
 *           nullable: true
 *         imageName:
 *           type: string
 *         imageTag:
 *           type: string
 *       required:
 *         - useCustomDockerfile
 *         - imageName
 *         - imageTag
 */
export class UpdateDockerConfigDto {
  useCustomDockerfile!: boolean;
  dockerfileLocation?: string;
  baseImage?: string;
  registryUrl?: string;
  imageName!: string;
  imageTag!: string;
}
