export const BRAND_FOOTER_SECTION_PROMPT = `
You are a branding and UI expert specializing in creating sophisticated, professional footers for brand identity documents. Design a comprehensive footer that reinforces brand credibility and provides essential information.

OUTPUT RULES:
- Generate ONLY HTML using Tailwind CSS utility classes
- Output must be one single line with all line breaks removed
- No custom CSS, no JavaScript, only Tailwind
- Layout must fit within an A4 portrait format (210mm x 297mm)
- Include modern design elements and professional styling

COMPREHENSIVE STRUCTURE:
<footer class="w-full mt-20 bg-gradient-to-b from-gray-50 to-gray-100 border-t border-gray-200">
  <div class="max-w-7xl mx-auto px-8 py-12">
    <!-- Main Footer Content -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-12 mb-12">
      <!-- Brand Section -->
      <div class="lg:col-span-1">
        <div class="flex items-center gap-4 mb-6">
          <div class="w-12 h-12 bg-gradient-to-br from-blue-600 via-purple-600 to-indigo-700 rounded-2xl flex items-center justify-center shadow-lg">
            <span class="text-white text-xl font-black">{{brand_initial}}</span>
          </div>
          <div>
            <h3 class="text-xl font-bold text-gray-900">{{brand_name}}</h3>
            <p class="text-sm text-gray-600 font-medium">Brand Guidelines</p>
          </div>
        </div>
        <p class="text-sm text-gray-700 leading-relaxed mb-6">This comprehensive brand guide ensures consistent visual identity across all touchpoints, maintaining professional standards and brand integrity.</p>
        <div class="flex items-center gap-4">
          <div class="flex items-center gap-2 text-xs text-gray-500">
            <div class="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
            <span>Version 1.0</span>
          </div>
          <div class="flex items-center gap-2 text-xs text-gray-500">
            <div class="w-2 h-2 bg-blue-500 rounded-full"></div>
            <span>Updated {{current_date}}</span>
          </div>
        </div>
      </div>
      
      <!-- Document Information -->
      <div class="lg:col-span-1">
        <h4 class="text-lg font-bold text-gray-900 mb-6 flex items-center gap-2">
          <div class="w-1 h-6 bg-gradient-to-b from-blue-600 to-purple-600 rounded-full"></div>
          Document Details
        </h4>
        <div class="space-y-4">
          <div class="bg-white rounded-xl p-4 border border-gray-200 shadow-sm">
            <div class="flex items-center justify-between mb-2">
              <span class="text-sm font-semibold text-gray-700">Creation Date</span>
              <span class="text-sm text-gray-600">{{creation_date}}</span>
            </div>
            <div class="flex items-center justify-between mb-2">
              <span class="text-sm font-semibold text-gray-700">Last Modified</span>
              <span class="text-sm text-gray-600">{{modification_date}}</span>
            </div>
            <div class="flex items-center justify-between">
              <span class="text-sm font-semibold text-gray-700">Document ID</span>
              <span class="text-xs font-mono text-gray-500 bg-gray-100 px-2 py-1 rounded">{{document_id}}</span>
            </div>
          </div>
          <div class="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-xl p-4 border border-blue-200">
            <div class="flex items-center gap-2 mb-2">
              <svg class="w-4 h-4 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path>
              </svg>
              <span class="text-sm font-semibold text-blue-900">Generated by AI</span>
            </div>
            <p class="text-xs text-blue-800">This document was created using advanced AI technology to ensure consistency and professional quality.</p>
          </div>
        </div>
      </div>
      
      <!-- Contact & Legal -->
      <div class="lg:col-span-1">
        <h4 class="text-lg font-bold text-gray-900 mb-6 flex items-center gap-2">
          <div class="w-1 h-6 bg-gradient-to-b from-purple-600 to-pink-600 rounded-full"></div>
          Contact Information
        </h4>
        <div class="space-y-4">
          <div class="bg-white rounded-xl p-4 border border-gray-200 shadow-sm">
            <div class="space-y-3">
              <div class="flex items-center gap-3">
                <div class="w-8 h-8 bg-blue-100 rounded-lg flex items-center justify-center">
                  <svg class="w-4 h-4 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                    <path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z"></path>
                    <path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z"></path>
                  </svg>
                </div>
                <div>
                  <p class="text-sm font-medium text-gray-900">{{contact_email}}</p>
                  <p class="text-xs text-gray-600">Brand inquiries</p>
                </div>
              </div>
              <div class="flex items-center gap-3">
                <div class="w-8 h-8 bg-green-100 rounded-lg flex items-center justify-center">
                  <svg class="w-4 h-4 text-green-600" fill="currentColor" viewBox="0 0 20 20">
                    <path d="M2 3a1 1 0 011-1h2.153a1 1 0 01.986.836l.74 4.435a1 1 0 01-.54 1.06l-1.548.773a11.037 11.037 0 006.105 6.105l.774-1.548a1 1 0 011.059-.54l4.435.74a1 1 0 01.836.986V17a1 1 0 01-1 1h-2C7.82 18 2 12.18 2 5V3z"></path>
                  </svg>
                </div>
                <div>
                  <p class="text-sm font-medium text-gray-900">{{contact_phone}}</p>
                  <p class="text-xs text-gray-600">Business hours</p>
                </div>
              </div>
            </div>
          </div>
          
          <div class="bg-gradient-to-r from-amber-50 to-orange-50 rounded-xl p-4 border border-amber-200">
            <div class="flex items-start gap-2">
              <svg class="w-4 h-4 text-amber-600 mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd"></path>
              </svg>
              <div>
                <p class="text-sm font-semibold text-amber-900 mb-1">Confidential Document</p>
                <p class="text-xs text-amber-800 leading-relaxed">This brand guide contains proprietary information. Distribution is restricted to authorized personnel only.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <!-- Footer Bottom -->
    <div class="border-t border-gray-300 pt-8">
      <div class="flex flex-col md:flex-row justify-between items-center gap-6">
        <div class="flex flex-col md:flex-row items-center gap-6">
          <div class="text-center md:text-left">
            <p class="text-sm font-semibold text-gray-900">© {{current_year}} {{company_name}}</p>
            <p class="text-xs text-gray-600">All rights reserved. Brand guidelines and assets are protected by copyright.</p>
          </div>
        </div>
        
        <div class="flex items-center gap-6">
          <div class="flex items-center gap-2 bg-white rounded-full px-4 py-2 border border-gray-200 shadow-sm">
            <div class="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
            <span class="text-xs font-medium text-gray-700">Active Guidelines</span>
          </div>
          <div class="text-right">
            <p class="text-xs text-gray-500">Generated on {{generation_timestamp}}</p>
            <p class="text-xs text-gray-400">Powered by AI Brand Systems</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <!-- Subtle Brand Accent -->
  <div class="h-1 bg-gradient-to-r from-blue-600 via-purple-600 to-indigo-600"></div>
</footer>

STYLE GUIDELINES:
- Professional, sophisticated design with modern elements
- Consistent use of brand colors and gradients
- Clear information hierarchy and visual organization
- Responsive layout optimized for various screen sizes
- Subtle animations and micro-interactions for engagement
- Comprehensive contact and legal information
- Status indicators for document freshness and authenticity

CONTENT REPLACEMENT RULES:
- Replace {{brand_initial}} with first letter of brand name
- Replace {{brand_name}} with actual brand name from project
- Replace {{company_name}} with company name
- Replace {{contact_email}} and {{contact_phone}} with actual contact info
- Replace {{current_date}}, {{current_year}}, {{creation_date}}, {{modification_date}} with appropriate dates
- Replace {{document_id}} with unique identifier
- Replace {{generation_timestamp}} with current timestamp

PROJECT CONTEXT:
{{project_context}}
`;
