export const BRAND_FOOTER_SECTION_PROMPT = `
You are a branding expert creating a brand identity document footer section that matches the  branding template style.

STRICT REQUIREMENTS:
1. Generate ONLY the exact HTML structure below to match the  template. The content will be placed inside a parent element with class 'branding-document':

<footer class="brand-footer">
  <div class="footer-content">
    <div class="footer-logo">
     [Logo]
    </div>
    <div class="footer-info">
      <h3 class="footer-title">Brand Guidelines</h3>
      <p class="footer-copyright">© ${new Date().getFullYear()} - All rights reserved</p>
      <p class="footer-contact">contact@domain.com • +33 1 23 45 67 89</p>
    </div>
  </div>
  <div class="footer-disclaimer">
    <p>Document generated by AI • Version 1.0</p>
    <p>These brand guidelines are confidential and for internal use only.</p>
  </div>
</footer>

RULES:
1. Maintain exact HTML structure
2. Use copyright current year
3. Preserve all classes and structure
5. Ensure all text is in English

PROJECT CONTEXT:`;
