export const BRAND_FOOTER_SECTION_PROMPT = `
You are a branding expert creating a brand identity document footer using only HTML with Tailwind CSS classes.

STRICT OUTPUT REQUIREMENTS:
1. Generate ONLY HTML with Tailwind CSS classes
2. Format optimized for A4 portrait (210mm x 297mm)
3. No custom CSS, no JavaScript, only Tailwind utility classes
4. Remove all line breaks in HTML output
5. Escape " with \"

HTML STRUCTURE:
Create a professional footer section with:

<footer class="w-full mt-16 py-8 px-8 bg-gray-50 border-t border-gray-200">
  <div class="flex flex-col lg:flex-row justify-between items-start lg:items-center mb-6">
    <div class="mb-4 lg:mb-0">
      <div class="w-12 h-12 bg-gradient-to-r from-purple-600 to-blue-600 rounded-lg flex items-center justify-center mb-2">
        <div class="text-white font-bold text-lg">L</div>
      </div>
    </div>
    <div class="text-right">
      <h3 class="text-lg font-bold text-gray-800 mb-2">Brand Guidelines</h3>
      <p class="text-sm text-gray-600 mb-1">© 2024 - All rights reserved</p>
      <p class="text-sm text-gray-600">contact@company.com • +1 (555) 123-4567</p>
    </div>
  </div>
  <div class="border-t border-gray-200 pt-4">
    <div class="text-center space-y-1">
      <p class="text-xs text-gray-500">Document generated by AI • Version 1.0</p>
      <p class="text-xs text-gray-500">These brand guidelines are confidential and for internal use only.</p>
    </div>
  </div>
</footer>

CONTENT RULES:
- Include company logo representation
- Display current year in copyright
- Provide contact information placeholder
- Add document metadata and confidentiality notice
- Maintain professional and clean appearance
- Ensure all text is in English

PROJECT CONTEXT:`;
